"use strict";

// Faction type constants
const FACTION_TYPE = {
  POLICE: "police",
  FIRE: "fire",
  EMS: "ems",
  OTHER: "other",
};

const FACTIONS = {
  lspd: {
    name: "Los Santos Police Department",
    short: "LSPD",
    emailDomain: "lspd.online",
    icon: "assets/lspd_192.png",
    type: FACTION_TYPE.POLICE,
    cardBg: "#f5f0dc",
    cardBorder: "#c8b97a",
    businessCard: {
      header: "LOS SANTOS POLICE DEPARTMENT",
      badge: "assets/lspd_badge.png",
      recruitName: "LSPD",
      recruitPhone: "(866) 444-LSPD",
      websiteMain: "www.LSPDonline.org",
      websiteJoin: "www.joinLSPD.org",
    },
    ranks: [
      "Police Officer I",
      "Police Officer II",
      "Police Officer III",
      "Police Officer III+1",
      "Detective I",
      "Detective II",
      "Detective III",
      "Police Administrator I",
      "Police Administrator II",
      "Police Administrator III",
      "Sergeant I",
      "Sergeant II",
      "Lieutenant I",
      "Lieutenant II",
      "Captain I",
      "Captain II",
      "Captain III",
      "Commander",
      "Deputy Chief",
      "Assistant Chief of Police",
      "Chief of Police",
    ],
    seniorRanks: [
      "Lieutenant I",
      "Lieutenant II",
      "Captain I",
      "Captain II",
      "Captain III",
      "Commander",
      "Deputy Chief",
      "Assistant Chief of Police",
      "Chief of Police",
    ],
    midRanks: ["Sergeant I", "Sergeant II", "Detective I", "Detective II", "Detective III"],
    divisions: [
      "Patrol Division",
      "Detective Bureau",
      "Metropolitan Division",
      "Training Division",
      "SWAT",
      "Traffic Division",
      "Air Support Division",
      "Gang and Narcotics Division",
      "Internal Affairs Division",
      "Major Crimes Division",
      "Robbery-Homicide Division",
      "Force Investigation Division",
    ],
  },

  lssd: {
    name: "Los Santos County Sheriff's Department",
    short: "LSSD",
    emailDomain: "lssd.gov",
    icon: "assets/lssd_192.png",
    type: FACTION_TYPE.POLICE,
    cardBg: "#f5ecd5",
    cardBorder: "#94682C",
    businessCard: {
      header: "LOS SANTOS COUNTY SHERIFF'S DEPARTMENT",
      badge: "assets/lssd_192.png",
      recruitName: "LSSD",
      recruitPhone: "(866) 444-LSSD",
      websiteMain: "www.LSSDonline.org",
      websiteJoin: "www.joinLSSD.org",
    },
    ranks: [
      "Deputy Sheriff",
      "Bonus Deputy Sheriff",
      "Deputy Sheriff (Master Field Training Officer)",
      "Sergeant",
      "Lieutenant",
      "Captain",
      "Area Commander",
      "Division chief",
      "Assistant Sheriff",
      "Undersheriff",
      "Sheriff",
    ],
    seniorRanks: ["Lieutenant", "Captain", "Area Commander", "Division chief", "Assistant Sheriff", "Undersheriff", "Sheriff"],
    midRanks: ["Sergeant", "Deputy Sheriff (Master Field Training Officer)"],
    divisions: [
      "Patrol Division",
      "Traffic Division",
      "Major Crimes Bureau",
      "Operation Safe Streets Bureau",
      "Court Services Division",
      "Custody Division",
      "Special Enforcement Bureau",
      "Emergency Services Detail",
      "Training Division",
      "Professional Standards Division",
      "Aero Bureau",
    ],
  },

  bcso: {
    name: "Blaine County Sheriff's Office",
    short: "BCSO",
    emailDomain: "bcso.gov",
    icon: "assets/bcso_192.png",
    type: FACTION_TYPE.POLICE,
    cardBg: "#e8f0e0",
    cardBorder: "#5a8a30",
    businessCard: {
      header: "BLAINE COUNTY SHERIFF'S OFFICE",
      badge: "assets/bcso_192.png",
      recruitName: "BCSO",
      recruitPhone: "(866) 444-BCSO",
      websiteMain: "www.BCSOonline.org",
      websiteJoin: "www.joinBCSO.org",
    },
    ranks: [
      "Deputy Sheriff Trainee",
      "Deputy Sheriff",
      "Senior Deputy",
      "Sergeant",
      "Lieutenant",
      "Captain",
      "Commander",
      "Assistant Sheriff",
      "Undersheriff",
      "Sheriff",
    ],
    seniorRanks: ["Lieutenant", "Captain", "Commander", "Assistant Sheriff", "Undersheriff", "Sheriff"],
    midRanks: ["Sergeant"],
    divisions: [
      "Patrol Division",
      "Traffic Division",
      "Major Crimes Bureau",
      "Operation Safe Streets Bureau",
      "Court Services Division",
      "Custody Division",
      "Special Enforcement Bureau",
      "Emergency Services Detail",
      "Training Division",
      "Professional Standards Division",
      "Air Support Bureau",
    ],
  },

  sahp: {
    name: "San Andreas Highway Patrol",
    short: "SAHP",
    emailDomain: "sahp.gov",
    icon: "assets/sahp_192.png",
    type: FACTION_TYPE.POLICE,
    cardBg: "#D2E4F1",
    cardBorder: "#447CC0",
    businessCard: {
      header: "SAN ANDREAS HIGHWAY PATROL",
      badge: "assets/sahp_192.png",
      recruitName: "SAHP",
      recruitPhone: "(866) 444-SAHP",
      websiteMain: "www.SAHPonline.org",
      websiteJoin: "www.joinSAHP.org",
    },
    ranks: [
      "Probationary Officer",
      "Officer",
      "Sergeant",
      "Lieutenant",
      "Captain",
      "Assistant Chief",
      "Chief",
      "Assistant Commissioner",
      "Deputy Commissioner",
      "Commissioner",
    ],
    seniorRanks: ["Lieutenant", "Captain", "Assistant Chief", "Chief", "Assistant Commissioner", "Deputy Commissioner", "Commissioner"],
    midRanks: ["Sergeant"],
    divisions: [
      "Patrol Division",
      "Traffic Division",
      "Commercial Vehicle Enforcement Division",
      "Special Weapons and Tactics",
      "Multi-disciplinary Accident Investigation Team",
      "Special Response Team (SRT)",
      "Governor's Protective Detail",
      "Judicial Protection Detail",
      "Dignitary Protection Detail",
      "Capitol Protection Detail",
      "Training Division",
      "Professional Standards Division",
      "Community Oriented Policing",
    ],
  },
  lscofd: {
    name: "Los Santos County Fire Department",
    short: "LSCoFD",
    emailDomain: "lscofd.gov",
    icon: "assets/lscofd_192.png",
    type: FACTION_TYPE.FIRE,
    cardBg: "#f5e8e0",
    cardBorder: "#c04020",
    businessCard: {
      header: "LOS SANTOS COUNTY FIRE DEPARTMENT",
      badge: "assets/lscofd_192.png",
      recruitName: "LSCoFD",
      recruitPhone: "(866) 444-LSCoFD",
      websiteMain: "www.LSCoFDonline.org",
      websiteJoin: "www.joinLSCoFD.org",
    },
    ranks: [
      "Firefighter Trainee",
      "Firefighter EMT",
      "Firefighter Paramedic",
      "Captain",
      "Battalion Chief",
      "Assistant Chief",
      "Deputy Chief",
      "Chief Deputy",
      "Fire Chief",
      "Assistant Fire Commissioner",
      "Fire Commissioner",
    ],
    seniorRanks: ["Assistant Chief", "Deputy Chief", "Chief Deputy", "Fire Chief", "Assistant Fire Commissioner", "Fire Commissioner"],
    midRanks: ["Battalion Chief", "Captain"],
    divisions: [
      "Emergency Operations Bureau",
      "Business Operations Bureau",
      "Leadership & Professional Standards Bureau",
      "Homeland Security Section",
      "Training & EMS Bureau",
      "Training Services Division",
      "North Operations Bureau",
      "Central Operations Bureau",
      "East Operations Bureau",
      "Community Risk Reduction Bureau",
      "Administrative Services Bureau",
      "Special Services Bureau",
      "Fire Prevention Division",
      "Health Haz Mat Division",
      "Forestry Division",
      "Compliance Section",
      "Planning and Grants Division",
      "Communications Division",
      "Financial Management Division",
      "Materials Management Division",
      "Information Management Division",
      "Human Resources Division",
      "Command & Control Division",
      "Construction & Maintenance Division",
      "Fleet Services Division",
      "Air Support Bureau",
      "Air Operations Division",
      "Employee Relations Section",
      "Wellness Section",
      "Professional Performance Section",
      "Risk Management Section",
      "Organizational Development Section",
      "Disability Management & Compliance Section",
    ],
  },
  lsfd: {
    name: "Los Santos Fire Department",
    short: "LSFD",
    emailDomain: "lsfd.online",
    icon: "assets/lsfd_192.png",
    type: FACTION_TYPE.FIRE,
    cardBg: "#f5e8e0",
    cardBorder: "#cb2020",
    businessCard: {
      header: "LOS SANTOS FIRE DEPARTMENT",
      badge: "assets/lsfd_192.png",
      recruitName: "LSFD",
      recruitPhone: "(866) 444-LSFD",
      websiteMain: "www.LSFDonline.org",
      websiteJoin: "www.joinLSFD.org",
    },
    ranks: [
      "Firefighter I / EMT",
      "Firefighter II / EMT",
      "Firefighter III / EMT",
      "Firefighter III / Paramedic",
      "Engineer",
      "Apparatus Operator",
      "Captain I",
      "Captain II",
      "Battalion Chief",
      "Assistant Chief",
      "Deputy Chief",
      "Fire Chief",
    ],
    seniorRanks: ["Captain II", "Battalion Chief", "Assistant Chief", "Deputy Chief", "Fire Chief"],
    midRanks: ["Engineer", "Apparatus Operator", "Captain I"],
    divisions: [
      "Operations Bureau",
      "Emergency Services Bureau",
      "Professional Standards Division",
      "Community Liaison Officer",
      "Administrative Services Bureau",
      "Fire Prevention Bureau",
      "Information and Technology Bureau",
      "Training and Support Bureau",
      "Homeland Security & Arson",
      "Urban Search & Rescue",
      "Hazmat",
      "Air Operations",
      "Dive Team",
      "Mobile Medics",
      "Metropolitan Fire Communications",
    ],
  },
};
