"use strict";

const FACTIONS = {
  lspd: {
    name: "Los Santos Police Department",
    short: "LSPD",
    emailDomain: "lspd.online",
    cardBg: "#f5f0dc",
    cardBorder: "#c8b97a",
    ranks: [
      "Police Officer I",
      "Police Officer II",
      "Police Officer III",
      "Detective I",
      "Detective II",
      "Detective III",
      "Sergeant I",
      "Sergeant II",
      "Lieutenant I",
      "Lieutenant II",
      "Captain I",
      "Captain II",
      "Captain III",
      "Commander",
      "Deputy Chief",
      "Assistant Chief of Police",
      "Chief of Police",
    ],
    seniorRanks: [
      "Lieutenant I",
      "Lieutenant II",
      "Captain I",
      "Captain II",
      "Captain III",
      "Commander",
      "Deputy Chief",
      "Assistant Chief of Police",
      "Chief of Police",
    ],
    midRanks: ["Sergeant I", "Sergeant II", "Detective I", "Detective II", "Detective III"],
    divisions: [
      "Patrol Division",
      "Detective Bureau",
      "Metropolitan Division",
      "Training Division",
      "SWAT",
      "Traffic Division",
      "Air Support Division",
      "Gang and Narcotics Division",
      "Internal Affairs Division",
      "Major Crimes Division",
      "Robbery-Homicide Division",
      "Force Investigation Division",
    ],
  },

  lssd: {
    name: "Los Santos County Sheriff's Department",
    short: "LSSD",
    emailDomain: "lssd.gov",
    cardBg: "#f5ecd5",
    cardBorder: "#a07830",
    ranks: [
      "Deputy Sheriff",
      "Bonus Deputy Sheriff",
      "Deputy Sheriff (Master Field Training Officer)",
      "Sergeant",
      "Lieutenant",
      "Captain",
      "Area Commander",
      "Division chief",
      "Assistant Sheriff",
      "Undersheriff",
      "Sheriff",
    ],
    seniorRanks: ["Lieutenant", "Captain", "Area Commander", "Division chief", "Assistant Sheriff", "Undersheriff", "Sheriff"],
    midRanks: ["Sergeant", "Deputy Sheriff (Master Field Training Officer)"],
    divisions: [
      "Patrol Division",
      "Traffic Division",
      "Major Crimes Bureau",
      "Operation Safe Streets Bureau",
      "Court Services Division",
      "Custody Division",
      "Special Enforcement Detail",
      "Emergency Services Detail",
      "Training Division",
      "Professional Standards Division",
      "Air Support Bureau",
    ],
  },
};
